### ISSUE TITLE
error C2338: INVALID_MATRIX_TEMPLATE_PARAMETERS	

### ISSUE THREAD

**Issue by luck-boy1994** [yaoyx689/Fast-Robust-ICP#1]
When i debug the code，there are several errors occurred in the program 
error C2719: “m”: The parameter with __declspec(align('16')) will not be aligned in icp.h
error C2719: “v”: The parameter with __declspec(align('16')) will not be aligned  in icp.h
The  error is that the variable w is defined as vectorx, but the parameter type of the function ( get_energy) is vectorxd。in file FRICP.h
When I changed vectorx to vectorxd, the second error occurred，error C2338: INVALID_MATRIX_TEMPLATE_PARAMETERS	
The program does not prompt me which line is wrong，in file FRICP.h
The compilation platform is windows vs2013, releasex86,could you help me solve these problems。thanks.

**Comment by yaoyx689** [comment]
Hello, this should be a problem of Eigen library compilation. Do you set the　“Code generation”－》 “Structure member alignment” is the default in Vs?
