### ISSUE TITLE
only demo works.

### ISSUE THREAD

**Issue by yaoyishen** [yaoyx689/Fast-Robust-ICP#2]
only demo works.
My point cloud has about 200000 points.the code can't work.

**Comment by bldeng** [comment]
> only demo works.
> 
> My point cloud has about 200000 points.the code can't work.

Thanks for your feedback. Could you please provide more information about the issue you are facing? For example, did the program crash? Was it an issue with speed or accuracy? Thanks.

**Comment by yaoyishen** [comment]
I got result after along time.The result is not so good.

**Comment by yaoyishen** [comment]
I got result after along time.The result is not so good. Should I provide a good initial?

**Comment by yaoyishen** [comment]
I got result after a along time.The result is not so good. Should I provide a good initial?

**Comment by bldeng** [comment]
> I got result after along time.The result is not so good.

Thank you.

Please note that like other registration methods, our algorithm has its limitations and is not guaranteed to work well for every possible configuration. For example, poor initialization may lead to inaccurate alignment as the method is solving a nonconvex optimization problem.

**Comment by yaoyishen** [comment]
Thank you! I will provide a good initialization to have a test.

**Comment by yaoyishen** [comment]
Good initialization ensures good result.The code has a high precision.

Thank you.
