### ISSUE TITLE
请问这个方法能用于5个自由度的配准吗

### ISSUE THREAD

**Issue by MZener** [yaoyx689/Fast-Robust-ICP#25]
我想让配准的结果只考虑xy轴的旋转，和xyz轴的平移，请问这个方法能用于这样的需求吗，多谢。

**Comment by yaoyx689** [comment]
您好，本方法不能满足这个需求，您需要在求解旋转变换时重新推导公式并做相应的修改才可适用。

**Comment by MZener** [comment]
> 您好，本方法不能满足这个需求，您需要在求解旋转变换时重新推导公式并做相应的修改才可适用。

Eigen::Affine3d transformation;
        Eigen::LDLT<Matrix66> ldlt(LHS);
        RHS = ldlt.solve(RHS);
        transformation = Eigen::AngleAxisd(RHS(0), Eigen::Vector3d::UnitX()) *
                Eigen::AngleAxisd(RHS(1), Eigen::Vector3d::UnitY()) *
                Eigen::AngleAxisd(RHS(2), Eigen::Vector3d::UnitZ());
        transformation.translation() = RHS.tail<3>();

请问这个位置是算出最优的旋转矩阵吗，这里把RHS(2)改成0能起到效果么(绕着Z轴的旋转角度始终为0)？如果原始点云到目标点云就只做上面5个自由度的变换，这里求解的旋转矩阵即使存在Z轴角度也不去做修正，配准迭代能到最后能得到合适的结果么？
transformation = Eigen::AngleAxisd(RHS(0), Eigen::Vector3d::UnitX()) *
                Eigen::AngleAxisd(RHS(1), Eigen::Vector3d::UnitY()) *
                Eigen::AngleAxisd(0, Eigen::Vector3d::UnitZ());

**Comment by yaoyx689** [comment]
看上去是可行的，但是我没有尝试过。

**Comment by MZener** [comment]
> 看上去是可行的，但是我没有尝试过。

确实能得到结果，不知道精度会不会有差异。
