### ISSUE TITLE
Initial setup

### ISSUE THREAD

**Issue by kidpaul94** [yaoyx689/Fast-Robust-ICP#3]
Thank you for the work!
I'm currently trying to setup the environment to test the Fast-Robust-ICP.

I downloaded Cmake and Eigen using following command lines:
sudo apt install cmake (3.16.3 version)
sudo apt-get install libeigen3-dev (3.3.7-2 version)

I got the following result when compiling the repo with "cmake .":

-- Found NanoFlann: /home/kidpaul/Fast-Robust-ICP/include
ln: '/home/kidpaul/Fast-Robust-ICP/data' and './data' are the same file
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kidpaul/Fast-Robust-ICP

The issue is that I'm not sure whether I compiled the files properly since I can't execute the command ./FRICP. 
(I just got cmake_install.cmake file when I ran the cmake command and it doesn't look a right compiling process)

Could you give me some further guide how to setup the environment?
(I'm running this under Ubuntu 20.04. Not sure whether this can be a possible issue)

**Comment by bldeng** [comment]
Did you run "make" to compile the source code after running CMake? CMake only configures the project and generates the makefile. You still need to use the make command to compile the source code.

**Comment by kidpaul94** [comment]
Oh, I totally forgot about that... my bad. Thank you for pointing it out! I'll close this issue.

**Comment by kidpaul94** [comment]
Thank you for pointing that out. I totally forgot about it.

2021년 3월 26일 (금) 오후 7:47, Bailin Deng ***@***.***>님이 작성:
