### ISSUE TITLE
Points on a line as the result

### ISSUE THREAD

**Issue by MoyGcc** [yaoyx689/Fast-Robust-ICP#4]
Hi, 

thank you for this wonderful work. I'm testing this code on my own data. Despite the target and source input (meshes) have already a roughly good overlay, I got many points on a line as the registered result. I upload these two files in this drive. Thank you for your clarification in advance! https://drive.google.com/drive/folders/1Mt26annG3yEZFbAU-xGgik6O0UDAxdC6?usp=sharing

**Comment by MoyGcc** [comment]
The input format is somehow restricted to .obj, though the output is in .ply. If something weird happens while using this ICP method, try to convert the inputs to obj files.

**Comment by yaoyx689** [comment]
Hi, this problem is because the code does not support binary-encoded .ply format, but non-binary-encoded .ply format is supported.

**Comment by MoyGcc** [comment]
> Hi, this problem is because the code does not support binary-encoded .ply format, but non-binary-encoded .ply format is supported.

Ah, I see. Thank you for the clarification.
