### ISSUE TITLE
请教文章图片制作问题

### ISSUE THREAD

**Issue by paperID2381** [yaoyx689/Fast-Robust-ICP#6]
您好！请教一个代码无关的问题：请问您们论文里的点云可视化和点云误差显示采用什么软件制作的？论文里面的图片很美观，想学习学习，谢谢

**Comment by yaoyx689** [comment]
你好~ 我们的点云可视化是用 vtkplotter库 (http://github.com/jtpils/vtkplotter) 写python脚本做的，点云误差图是先根据误差的最大最小值 计算出colorbar中对应的RGB值，用该值给点云每个点赋颜色， 之后也是用vtkplotter显示渲染的。

**Comment by momeak-liu** [comment]
您好， 我最近在学习使用vtkplotter库进行点云误差可视化，但是没有具体的思路，请问您是否能够共享一些代码或者学习资料，万分感谢！！
